name: 'Stop Nomad Job'
description: 'Handles stopping a given nomad job'
inputs:
  token:
    description: 'Token used to authenticate with a nomad server'
    required: true
  address:
    description: 'Address of the nomad server'
    required: true
  job_name:
    description: 'Name of the nomad job to stop'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.address }}
    - ${{ inputs.job_name }}
branding:
  icon: 'upload-cloud'
  color: 'green'
